app = "epstein-file-explorer"
primary_region = "iad"

[env]
  NODE_ENV = "production"
  PORT = "5000"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "suspend"
  force_https = true
  internal_port = 5_000
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "requests"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory = "1gb"