# fly.toml app configuration file generated for epstein-typesense on 2026-02-18T20:44:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'epstein-typesense'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  TYPESENSE_DATA_DIR = '/data'

[[mounts]]
  source = 'typesense_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8108
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 8108

[[vm]]
  size = 'shared-cpu-4x'
  memory = '8gb'
